@StockLab.Api_HostAddress = http://localhost:5274

GET {{StockLab.Api_HostAddress}}/health
Accept: text/plain

###

GET {{StockLab.Api_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{StockLab.Api_HostAddress}}/api/stocks/AAPL/quote
Accept: application/json

###

GET {{StockLab.Api_HostAddress}}/api/stocks/INVALID/quote
Accept: application/json

###

GET {{StockLab.Api_HostAddress}}/api/stocks/%20/quote
Accept: application/json

###

GET {{StockLab.Api_HostAddress}}/api/stocks/search?query=apple
Accept: application/json

###

GET {{StockLab.Api_HostAddress}}/api/stocks/search?query=zzzzzz
Accept: application/json

###

GET {{StockLab.Api_HostAddress}}/api/stocks/search
Accept: application/json

###

GET {{StockLab.Api_HostAddress}}/api/stocks/AAPL/history?from=2026-08-24&to=2026-08-29&interval=Day
Accept: application/json

###

GET {{StockLab.Api_HostAddress}}/api/stocks/AAPL/history?from=2026-08-25&to=2026-08-27&interval=Day
Accept: application/json

###

GET {{StockLab.Api_HostAddress}}/api/stocks/AAPL/history?from=2026-08-24T13:30:00Z&to=2026-08-29T13:30:00Z&interval=Hour
Accept: application/json

###
