// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockLab.Infrastructure.Persistence;

#nullable disable

namespace StockLab.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StockLabDbContext))]
    [Migration("20260923233129_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StockLab.Domain.Entities.Holding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AverageCost")
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(19,8)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId", "Symbol")
                        .IsUnique();

                    b.ToTable("Holdings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Holdings_AverageCost", "[AverageCost] > 0");

                            t.HasCheckConstraint("CK_Holdings_Quantity", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("StockLab.Domain.Entities.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CashBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(19,4)")
                        .HasDefaultValue(100000m);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("USD");

                    b.Property<decimal>("InitialCapital")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(19,4)")
                        .HasDefaultValue(100000m);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Portfolios", null, t =>
                        {
                            t.HasCheckConstraint("CK_Portfolios_CashBalance", "[CashBalance] >= 0");

                            t.HasCheckConstraint("CK_Portfolios_InitialCapital", "[InitialCapital] > 0");
                        });
                });

            modelBuilder.Entity("StockLab.Domain.Entities.PriceAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("USD");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(9)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("TargetPrice")
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime?>("TriggeredAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<decimal?>("TriggeredPrice")
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Currency")
                        .HasFilter("[Status] = 'Active'");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("PriceAlerts", null, t =>
                        {
                            t.HasCheckConstraint("CK_PriceAlerts_Condition", "[Condition] IN ('Above', 'Below')");

                            t.HasCheckConstraint("CK_PriceAlerts_Status", "[Status] IN ('Active', 'Disabled', 'Triggered')");

                            t.HasCheckConstraint("CK_PriceAlerts_TargetPrice", "[TargetPrice] > 0");

                            t.HasCheckConstraint("CK_PriceAlerts_TriggeredAtUtc", "[TriggeredAtUtc] IS NULL OR [TriggeredAtUtc] >= [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_PriceAlerts_TriggeredFields", "([Status] = 'Triggered' AND [TriggeredPrice] IS NOT NULL AND [TriggeredAtUtc] IS NOT NULL) OR ([Status] IN ('Active', 'Disabled') AND [TriggeredPrice] IS NULL AND [TriggeredAtUtc] IS NULL)");

                            t.HasCheckConstraint("CK_PriceAlerts_TriggeredPrice", "[TriggeredPrice] IS NULL OR [TriggeredPrice] > 0");

                            t.HasCheckConstraint("CK_PriceAlerts_UpdatedAtUtc", "[UpdatedAtUtc] >= [CreatedAtUtc]");
                        });
                });

            modelBuilder.Entity("StockLab.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExecutedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<decimal>("ExecutionPrice")
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(19,8)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("varchar(4)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(19,4)");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId", "OrderId")
                        .IsUnique();

                    b.HasIndex("PortfolioId", "ExecutedAtUtc", "Id");

                    b.HasIndex("PortfolioId", "Side", "ExecutedAtUtc");

                    b.HasIndex("PortfolioId", "Symbol", "ExecutedAtUtc");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_ExecutionPrice", "[ExecutionPrice] > 0");

                            t.HasCheckConstraint("CK_Transactions_Quantity", "[Quantity] > 0");

                            t.HasCheckConstraint("CK_Transactions_Side", "[Side] IN ('BUY', 'SELL')");

                            t.HasCheckConstraint("CK_Transactions_TotalAmount", "[TotalAmount] > 0");
                        });
                });

            modelBuilder.Entity("StockLab.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_DisplayName_NotBlank", "LTRIM(RTRIM([DisplayName])) <> ''");

                            t.HasCheckConstraint("CK_Users_Email_NotBlank", "LTRIM(RTRIM([Email])) <> ''");

                            t.HasCheckConstraint("CK_Users_NormalizedEmail_NotBlank", "LTRIM(RTRIM([NormalizedEmail])) <> ''");

                            t.HasCheckConstraint("CK_Users_PasswordHash_NotBlank", "LTRIM(RTRIM([PasswordHash])) <> ''");

                            t.HasCheckConstraint("CK_Users_UpdatedAtUtc", "[UpdatedAtUtc] >= [CreatedAtUtc]");
                        });
                });

            modelBuilder.Entity("StockLab.Domain.Entities.Watchlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Symbol")
                        .IsUnique();

                    b.ToTable("Watchlists", (string)null);
                });

            modelBuilder.Entity("StockLab.Domain.Entities.Holding", b =>
                {
                    b.HasOne("StockLab.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany("Holdings")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("StockLab.Domain.Entities.Portfolio", b =>
                {
                    b.HasOne("StockLab.Domain.Entities.User", "User")
                        .WithOne("Portfolio")
                        .HasForeignKey("StockLab.Domain.Entities.Portfolio", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockLab.Domain.Entities.PriceAlert", b =>
                {
                    b.HasOne("StockLab.Domain.Entities.User", "User")
                        .WithMany("PriceAlerts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockLab.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("StockLab.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany("Transactions")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("StockLab.Domain.Entities.Watchlist", b =>
                {
                    b.HasOne("StockLab.Domain.Entities.User", "User")
                        .WithMany("Watchlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockLab.Domain.Entities.Portfolio", b =>
                {
                    b.Navigation("Holdings");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("StockLab.Domain.Entities.User", b =>
                {
                    b.Navigation("Portfolio");

                    b.Navigation("PriceAlerts");

                    b.Navigation("Watchlists");
                });
#pragma warning restore 612, 618
        }
    }
}
